default:: all

94u.hpgl: 94.hpgl Makefile
	../../bin/hpgl_move 0 100 < 94.hpgl > 94u.hpgl
96u.hpgl: 96.hpgl Makefile
	../../bin/hpgl_move 0 100 < 96.hpgl > 96u.hpgl
126u.hpgl: 126.hpgl Makefile
	../../bin/hpgl_move 0 100 < 126.hpgl > 126u.hpgl
168u.hpgl: 168.hpgl Makefile
	../../bin/hpgl_move 0 100 < 168.hpgl > 168u.hpgl
176u.hpgl: 176.hpgl Makefile
	../../bin/hpgl_move 0 100 < 176.hpgl > 176u.hpgl
180u.hpgl: 180.hpgl Makefile
	../../bin/hpgl_move 0 100 < 180.hpgl > 180u.hpgl
184u.hpgl: 184.hpgl Makefile
	../../bin/hpgl_move 0 0 < 184.hpgl > 184u.hpgl
192.hpgl: 65.hpgl 96u.hpgl Makefile
	cat 65.hpgl 96u.hpgl > 192.hpgl

224.hpgl: 97.hpgl 96.hpgl Makefile
	cat 97.hpgl 96.hpgl > 224.hpgl

193.hpgl: 65.hpgl 180u.hpgl Makefile
	cat 65.hpgl 180u.hpgl > 193.hpgl

225.hpgl: 97.hpgl 180.hpgl Makefile
	cat 97.hpgl 180.hpgl > 225.hpgl

194.hpgl: 65.hpgl 94u.hpgl Makefile
	cat 65.hpgl 94u.hpgl > 194.hpgl

226.hpgl: 97.hpgl 94.hpgl Makefile
	cat 97.hpgl 94.hpgl > 226.hpgl

195.hpgl: 65.hpgl 126u.hpgl Makefile
	cat 65.hpgl 126u.hpgl > 195.hpgl

227.hpgl: 97.hpgl 126.hpgl Makefile
	cat 97.hpgl 126.hpgl > 227.hpgl

196.hpgl: 65.hpgl 168u.hpgl Makefile
	cat 65.hpgl 168u.hpgl > 196.hpgl

228.hpgl: 97.hpgl 168.hpgl Makefile
	cat 97.hpgl 168.hpgl > 228.hpgl

197.hpgl: 65.hpgl 176u.hpgl Makefile
	cat 65.hpgl 176u.hpgl > 197.hpgl

229.hpgl: 97.hpgl 176.hpgl Makefile
	cat 97.hpgl 176.hpgl > 229.hpgl

199.hpgl: 67.hpgl 184u.hpgl Makefile
	cat 67.hpgl 184u.hpgl > 199.hpgl

231.hpgl: 99.hpgl 184.hpgl Makefile
	cat 99.hpgl 184.hpgl > 231.hpgl

200.hpgl: 69.hpgl 96u.hpgl Makefile
	cat 69.hpgl 96u.hpgl > 200.hpgl

232.hpgl: 101.hpgl 96.hpgl Makefile
	cat 101.hpgl 96.hpgl > 232.hpgl

201.hpgl: 69.hpgl 180u.hpgl Makefile
	cat 69.hpgl 180u.hpgl > 201.hpgl

233.hpgl: 101.hpgl 180.hpgl Makefile
	cat 101.hpgl 180.hpgl > 233.hpgl

202.hpgl: 69.hpgl 94u.hpgl Makefile
	cat 69.hpgl 94u.hpgl > 202.hpgl

234.hpgl: 101.hpgl 94.hpgl Makefile
	cat 101.hpgl 94.hpgl > 234.hpgl

203.hpgl: 69.hpgl 168u.hpgl Makefile
	cat 69.hpgl 168u.hpgl > 203.hpgl

235.hpgl: 101.hpgl 168.hpgl Makefile
	cat 101.hpgl 168.hpgl > 235.hpgl

204.hpgl: 73.hpgl 96u.hpgl Makefile
	cat 73.hpgl 96u.hpgl > 204.hpgl

236.hpgl: 105.hpgl 96.hpgl Makefile
	cat 105.hpgl 96.hpgl > 236.hpgl

205.hpgl: 73.hpgl 180u.hpgl Makefile
	cat 73.hpgl 180u.hpgl > 205.hpgl

237.hpgl: 105.hpgl 180.hpgl Makefile
	cat 105.hpgl 180.hpgl > 237.hpgl

206.hpgl: 73.hpgl 94u.hpgl Makefile
	cat 73.hpgl 94u.hpgl > 206.hpgl

238.hpgl: 105.hpgl 94.hpgl Makefile
	cat 105.hpgl 94.hpgl > 238.hpgl

207.hpgl: 73.hpgl 168u.hpgl Makefile
	cat 73.hpgl 168u.hpgl > 207.hpgl

239.hpgl: 105.hpgl 168.hpgl Makefile
	cat 105.hpgl 168.hpgl > 239.hpgl

208.hpgl: 70.hpgl 45.hpgl Makefile
	cat 70.hpgl 45.hpgl > 208.hpgl

240.hpgl: 102.hpgl 45.hpgl Makefile
	cat 102.hpgl 45.hpgl > 240.hpgl

209.hpgl: 78.hpgl 126u.hpgl Makefile
	cat 78.hpgl 126u.hpgl > 209.hpgl

241.hpgl: 110.hpgl 126.hpgl Makefile
	cat 110.hpgl 126.hpgl > 241.hpgl

210.hpgl: 79.hpgl 96u.hpgl Makefile
	cat 79.hpgl 96u.hpgl > 210.hpgl

242.hpgl: 111.hpgl 96.hpgl Makefile
	cat 111.hpgl 96.hpgl > 242.hpgl

211.hpgl: 79.hpgl 180u.hpgl Makefile
	cat 79.hpgl 180u.hpgl > 211.hpgl

243.hpgl: 111.hpgl 180.hpgl Makefile
	cat 111.hpgl 180.hpgl > 243.hpgl

212.hpgl: 79.hpgl 94u.hpgl Makefile
	cat 79.hpgl 94u.hpgl > 212.hpgl

244.hpgl: 111.hpgl 94.hpgl Makefile
	cat 111.hpgl 94.hpgl > 244.hpgl

213.hpgl: 79.hpgl 126u.hpgl Makefile
	cat 79.hpgl 126u.hpgl > 213.hpgl

245.hpgl: 111.hpgl 126.hpgl Makefile
	cat 111.hpgl 126.hpgl > 245.hpgl

214.hpgl: 79.hpgl 168u.hpgl Makefile
	cat 79.hpgl 168u.hpgl > 214.hpgl

246.hpgl: 111.hpgl 168.hpgl Makefile
	cat 111.hpgl 168.hpgl > 246.hpgl

216.hpgl: 79.hpgl 47.hpgl Makefile
	cat 79.hpgl 47.hpgl > 216.hpgl

248.hpgl: 111.hpgl 47.hpgl Makefile
	cat 111.hpgl 47.hpgl > 248.hpgl

217.hpgl: 85.hpgl 96u.hpgl Makefile
	cat 85.hpgl 96u.hpgl > 217.hpgl

249.hpgl: 117.hpgl 96.hpgl Makefile
	cat 117.hpgl 96.hpgl > 249.hpgl

218.hpgl: 85.hpgl 180u.hpgl Makefile
	cat 85.hpgl 180u.hpgl > 218.hpgl

250.hpgl: 117.hpgl 180.hpgl Makefile
	cat 117.hpgl 180.hpgl > 250.hpgl

219.hpgl: 85.hpgl 94u.hpgl Makefile
	cat 85.hpgl 94u.hpgl > 219.hpgl

251.hpgl: 117.hpgl 94.hpgl Makefile
	cat 117.hpgl 94.hpgl > 251.hpgl

220.hpgl: 85.hpgl 168u.hpgl Makefile
	cat 85.hpgl 168u.hpgl > 220.hpgl

252.hpgl: 117.hpgl 168.hpgl Makefile
	cat 117.hpgl 168.hpgl > 252.hpgl

221.hpgl: 89.hpgl 180u.hpgl Makefile
	cat 89.hpgl 180u.hpgl > 221.hpgl

253.hpgl: 121.hpgl 180.hpgl Makefile
	cat 121.hpgl 180.hpgl > 253.hpgl

all:: 94u.hpgl 96u.hpgl 126u.hpgl 168u.hpgl 176u.hpgl 180u.hpgl 184u.hpgl 192.hpgl 224.hpgl 193.hpgl 225.hpgl 194.hpgl 226.hpgl 195.hpgl 227.hpgl 196.hpgl 228.hpgl 197.hpgl 229.hpgl 199.hpgl 231.hpgl 200.hpgl 232.hpgl 201.hpgl 233.hpgl 202.hpgl 234.hpgl 203.hpgl 235.hpgl 204.hpgl 236.hpgl 205.hpgl 237.hpgl 206.hpgl 238.hpgl 207.hpgl 239.hpgl 208.hpgl 240.hpgl 209.hpgl 241.hpgl 210.hpgl 242.hpgl 211.hpgl 243.hpgl 212.hpgl 244.hpgl 213.hpgl 245.hpgl 214.hpgl 246.hpgl 216.hpgl 248.hpgl 217.hpgl 249.hpgl 218.hpgl 250.hpgl 219.hpgl 251.hpgl 220.hpgl 252.hpgl 221.hpgl 253.hpgl

clean::
	rm 94u.hpgl 96u.hpgl 126u.hpgl 168u.hpgl 176u.hpgl 180u.hpgl 184u.hpgl 192.hpgl 224.hpgl 193.hpgl 225.hpgl 194.hpgl 226.hpgl 195.hpgl 227.hpgl 196.hpgl 228.hpgl 197.hpgl 229.hpgl 199.hpgl 231.hpgl 200.hpgl 232.hpgl 201.hpgl 233.hpgl 202.hpgl 234.hpgl 203.hpgl 235.hpgl 204.hpgl 236.hpgl 205.hpgl 237.hpgl 206.hpgl 238.hpgl 207.hpgl 239.hpgl 208.hpgl 240.hpgl 209.hpgl 241.hpgl 210.hpgl 242.hpgl 211.hpgl 243.hpgl 212.hpgl 244.hpgl 213.hpgl 245.hpgl 214.hpgl 246.hpgl 216.hpgl 248.hpgl 217.hpgl 249.hpgl 218.hpgl 250.hpgl 219.hpgl 251.hpgl 220.hpgl 252.hpgl 221.hpgl 253.hpgl
