#!/usr/bin/env python
import os
import sys
import serial

SCRIPTS_DIR = "scripts"

def _is_in_devel():
    d = os.path.split(os.path.dirname(os.path.abspath(__file__)))[1]
    return d == SCRIPTS_DIR

if __name__ == "__main__":
    if _is_in_devel():
        d = os.path.split(os.path.dirname(os.path.abspath(__file__)))[0]
        sys.path.insert(0, d)
        os.environ["PATH"] += ":%s" % (os.path.join(d, SCRIPTS_DIR))
    from autowriter import runner
    try:
        runner.run()
    except serial.serialutil.SerialException, e:
        print("Please plug your Arduino or setup the correct serial file: %s" % str(e))
        sys.exit(1)

